### ISSUE TITLE
Checkbox disappears from second page

### ISSUE THREAD

**Issue by ooii** [pdupavillon/strava-bulk-delete#1]
Hi Paul,

First, thanks for this extension. It saves life of a lot of people.
I wanted to test it today and it seems that it does work only in the first page of activities. Starting from the second one, the checkboxes disappear and it is no more possible to delete these activities ([screenshot](https://snag.gy/n6lyct.jpg)).
I'm running Chrome Version `66.0.3359.117` under `OSX 10.13.3 (17D102)`.

Thanks for your help.

**Comment by pdupavillon** [comment]
Hi @ooii,
I just released the fix (v 1.0.1).
Could you tell me if it's better ?

Thanks !

**Comment by ooii** [comment]
Thanks Paul, it works.
